export default [
  {
    id: 1,
    productName: "Black Jeans Pant",
    category: "Fashion",
    shop: "Fancy Store",
    discount: 10,
    offer: 20,
    description:
      "This pant is very confortable and It can be wear in any occusaions. While washing the color doesn't washed and it is in black color. Easy to wash.",
    quantity: 5,
    productPrice: 150,
    images: {
      0: "blackpant.webp",
      1: "blackpant1.webp",
      2: "blackpant2.webp",
      3: "blackpant3.webp",
    },
    productStatus: "verified",
    type: "male",
    mall: true,
  },
  {
    id: 2,
    productName: "Cap",
    category: "Fashion",
    shop: "Fancy Store",
    discount: 10,
    offer: 20,
    description:
      "This pant is very confortable and It can be wear in any occusaions. While washing the color doesn't washed and it is in black color. Easy to wash.",
    quantity: 5,
    productPrice: 150,
    images: {
      0: "cap.webp",
      1: "cap1.webp",
      2: "cap2.webp",
      3: "cap3.webp",
      4: "cap4.webp",
      5: "cap5.webp",
      6: "cap6.webp",
    },
    productStatus: "verified",
    type: "male",
    mall: true,
  },
  {
    id: 3,
    productName: "Jeans Pant",
    category: "Fashion",
    shop: "Fancy Store",
    discount: 10,
    offer: 20,
    description:
      "This pant is very confortable and It can be wear in any occusaions. While washing the color doesn't washed and it is in black color. Easy to wash.",
    quantity: 5,
    productPrice: 150,
    images: {
      0: "jeanspant.webp",
      1: "jeanspant2.webp",
      2: "jeanspant3.webp",
    },
    productStatus: "verified",
    type: "male",
    mall: true,
  },
  {
    id: 4,
    productName: "Jeans Pant",
    category: "Fashion",
    shop: "Fancy Store",
    discount: 10,
    offer: 20,
    description:
      "This pant is very confortable and It can be wear in any occusaions. While washing the color doesn't washed and it is in black color. Easy to wash.",
    quantity: 5,
    productPrice: 150,
    images: {
      0: "pant.webp",
      1: "pant2.webp",
      2: "pant3.webp",
      3: "pant4.webp",
      4: "pant5.webp",
      5: "pant6.webp",
    },
    productStatus: "verified",
    type: "male",
    mall: true,
  },
  {
    id: 5,
    productName: "T-Shirt",
    category: "Fashion",
    shop: "Fancy Store",
    discount: 10,
    offer: 20,
    description:
      "This pant is very confortable and It can be wear in any occusaions. While washing the color doesn't washed and it is in black color. Easy to wash.",
    quantity: 5,
    productPrice: 150,
    images: {
      0: "t-shirt.webp",
      1: "t-shirt1.webp",
      2: "t-shirt2.webp",
      3: "t-shirt3.webp",
    },
    productStatus: "verified",
    type: "male",
    mall: true,
  },
  {
    id: 6,
    productName: "white T-shirt",
    category: "Fashion",
    shop: "Fancy Store",
    discount: 10,
    offer: 20,
    description:
      "This pant is very confortable and It can be wear in any occusaions. While washing the color doesn't washed and it is in black color. Easy to wash.",
    quantity: 5,
    productPrice: 150,
    images: {
      0: "white.webp",
      1: "white1.webp",
      2: "white2.webp",
      3: "white3.webp",
      4: "white4.webp",
    },
    productStatus: "verified",
    type: "male",
    mall: true,
  },
  {
    id: 6,
    productName: "white Shoe",
    category: "Fashion",
    shop: "Fancy Store",
    discount: 10,
    offer: 20,
    description:
      "This pant is very confortable and It can be wear in any occusaions. While washing the color doesn't washed and it is in black color. Easy to wash.",
    quantity: 5,
    productPrice: 150,
    images: {
      0: "whiteshoe.webp",
      1: "whiteshoe2.webp",
      2: "whiteshoe3.webp",
      3: "whiteshoe4.webp",
    },
    productStatus: "verified",
    type: "male",
    mall: true,
  },
];